USE master;
GO

--DROP DATABASE MARKET_EXPRESS;
--GO

CREATE DATABASE MARKET_EXPRESS;
GO

USE MARKET_EXPRESS;
GO

CREATE TABLE Persona(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Nombre VARCHAR(40) NOT NULL,
	Email VARCHAR(40) UNIQUE NOT NULL,
	Telefono VARCHAR(40) NOT NULL,
	Cedula VARCHAR(12) NOT NULL,

	PRIMARY KEY(Id)
);
GO

CREATE TABLE Usuario(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Persona UNIQUEIDENTIFIER UNIQUE NOT NULL,
	Nombre_Acceso VARCHAR(7) UNIQUE NOT NULL,
	Clave_Acceso VARCHAR(80) NOT NULL,
	Tipo VARCHAR(15) NOT NULL,
	Estado VARCHAR(8),


	PRIMARY KEY(Id),
	FOREIGN KEY(Id_Persona) REFERENCES Persona(Id),
	CONSTRAINT CHK_Usuario_Tipo CHECK (Tipo = 'ADMINISTRADOR' OR Tipo = 'CLIENTE'),
	CONSTRAINT CHK_Usuario_Estado CHECK (Estado = 'ACTIVO' OR Estado = 'INACTIVO')
);
GO

CREATE TABLE Cliente(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Usuario UNIQUEIDENTIFIER UNIQUE NOT NULL,
	Cod_Cliente VARCHAR(10) NOT NULL,
	Verificado BIT NOT NULL,

	PRIMARY KEY(Id),
	FOREIGN KEY(Id_Usuario) REFERENCES Usuario(Id)
);
GO

CREATE TABLE Direccion(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Cliente UNIQUEIDENTIFIER NOT NULL,
	Nombre VARCHAR(10) NOT NULL,
	Descripcion VARCHAR(250) NOT NULL,

	PRIMARY KEY(Id)
);
GO

CREATE TABLE Bitacora_Acceso(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Usuario UNIQUEIDENTIFIER NOT NULL,
	Fecha_Inicio DATETIME NOT NULL,
	Fecha_Salida DATETIME,

	PRIMARY KEY(Id),
	FOREIGN KEY(Id_Usuario) REFERENCES Usuario(Id)
);
GO

CREATE TABLE Bitacora_Movimiento(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Usuario UNIQUEIDENTIFIER NOT NULL,
	Fecha DATETIME NOT NULL,
	Tipo VARCHAR(10) NOT NULL,
	Detalle Varchar(100) NOT NULL,

	PRIMARY KEY(Id),
	FOREIGN KEY(Id_Usuario) REFERENCES Usuario(Id)
);
GO

CREATE TABLE Inventario_Categoria(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Nombre VARCHAR(20) NOT NULL,
	Descripcion VARCHAR(200),
	Estado VARCHAR(8),

	PRIMARY KEY(Id),
	CONSTRAINT CHK_Categoria_Estado CHECK (Estado = 'ACTIVO' OR Estado = 'INACTIVO')
);
GO

CREATE TABLE Inventario_Articulo(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Categoria UNIQUEIDENTIFIER,
	Descripcion VARCHAR(255) NOT NULL,
	Codigo_Barras VARCHAR(255) NOT NULL,
	Precio DECIMAL(19,2) NOT NULL,
	Imagen VARCHAR(30),
	Estado VARCHAR(8),

	PRIMARY KEY(Id),
	CONSTRAINT CHK_Articulo_Estado CHECK (Estado = 'ACTIVO' OR Estado = 'INACTIVO')
);
GO

CREATE TABLE Carrito(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Cliente UNIQUEIDENTIFIER NOT NULL,
	Fecha_Apertura DATETIME NOT NULL,
	Estado VARCHAR(20) NOT NULL,

	PRIMARY KEY(Id),
	FOREIGN KEY(Id_Cliente) REFERENCES Cliente(Id),
	CONSTRAINT CHK_Carrito_Estado CHECK (Estado = 'ABIERTO' OR Estado = 'CERRADO')
);
GO

CREATE TABLE Carrito_Detalle(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Carrito UNIQUEIDENTIFIER NOT NULL,
	Id_Articulo UNIQUEIDENTIFIER NOT NULL

	PRIMARY KEY(Id),
	FOREIGN KEY(Id_Carrito) REFERENCES Carrito(Id),
	FOREIGN KEY(Id_Articulo) REFERENCES Inventario_Articulo(Id)
);
GO

CREATE TABLE Pedido(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Cliente UNIQUEIDENTIFIER NOT NULL,
	Fecha_Creacion DATETIME NOT NULL,
	Total DECIMAL(19,2) NOT NULL,

	PRIMARY KEY(Id),
);

CREATE TABLE Pedido_Detalle(
	Id UNIQUEIDENTIFIER DEFAULT newsequentialid(),
	Id_Pedido UNIQUEIDENTIFIER NOT NULL,
	Descripcion VARCHAR(255) NOT NULL,
	Codigo_Barras VARCHAR(255) NOT NULL,
	Precio DECIMAL(19,2) NOT NULL,

	PRIMARY KEY(Id),
	FOREIGN KEY(Id_Pedido) REFERENCES Pedido(Id),
);