// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.AppUserService.Create(Market_Express.Domain.Entities.AppUser,System.Collections.Generic.List{System.Guid},System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.RoleService.Create(Market_Express.Domain.Entities.Role,System.Collections.Generic.List{System.Guid},System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.RoleService.Edit(Market_Express.Domain.Entities.Role,System.Collections.Generic.List{System.Guid},System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.RoleService.ChangeStatus(System.Guid,System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.AppUserService.Edit(Market_Express.Domain.Entities.AppUser,System.Collections.Generic.List{System.Guid},System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.CartService.AddDetail(System.Guid,System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.CartService.UpdateDetail(System.Boolean,System.Guid,System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.CartService.DeleteDetail(System.Guid,System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.OrderService.Generate(System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.CartService.GenerateCartByOrderId(System.Guid,System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.AddressService.SetForUse(System.Guid,System.Guid)~System.Threading.Tasks.Task{Market_Express.Domain.BusisnessResult}")]
[assembly: SuppressMessage("Usage", "CA2200:Iniciar de nuevo para preservar los detalles de la pila", Justification = "<pendiente>", Scope = "member", Target = "~M:Market_Express.Domain.Services.BaseService.SaveWithTransaction(Market_Express.Domain.Abstractions.Repositories.IUnitOfWork)~System.Threading.Tasks.Task{System.Boolean}")]
